### ISSUE TITLE
Rofi fails to terminate on Super key when configured to

### ISSUE THREAD

**Issue by MagnusOxlund** [DaveDavenport/rofi#592]
I'm using the i3 window manager on a clean installation of the Manjaro Net edition, and I'm attempting to close Rofi with the Windows key on my keyboard.

Here is my approach:

In `~/.config/i3`:

`bindsym Mod1+d exec rofi -show drun -kb-cancel Super`

The expected behavior is that Rofi is launched by hitting Alt+d and is closed by hitting the Windows key.

Instead, when launched, Rofi fails to respond when the Windows key is pressed; nothing happens.

Binding keys other than "Super" to the `-kb-cancel` flag works just fine.

I'm using Rofi version 1.3.1, and my Rofi config file has not been modified.

**Comment by DaveDavenport** [comment]
You can not bind just a modifier key, Alt, Shift, etc. will also fail.
Planned to be fixed in the future (have a patch but is very nasty).

**Comment by MagnusOxlund** [comment]
Thanks for the quick response. It's always nice to know why something you try to do is unsuccessful. I'll be keeping an eye on the project. Thanks for pouring your time into it!

**Comment by MagnusOxlund** [comment]
In an attempt to find a temporary 3rd-party solution, I had a look at [ksuperkey](https://aur.archlinux.org/packages/ksuperkey/) which maps the Super key to Alt-F1. I discovered that `rofi -show drun -kb-cancel Alt+F1` doesn't respond either. Should I open a separate issue addressing this, or is this a known issue or maybe intentional behavior?

**Comment by DaveDavenport** [comment]
hmm interesting.. F1 works, Alt-F1 not.

**Comment by sardemff7** [comment]
Side issue fixed in master with xkbcommon 0.7.0+.

**Comment by DaveDavenport** [comment]
thx.

**Comment by sardemff7** [comment]
And asked feature added to master. @MagnusOxlund can you test please?

**Comment by MagnusOxlund** [comment]
Master tested and Alt+F1 issue confirmed to be fixed. Super as sole `-kb-cancel` argument still doesn't work, if I correctly interpreted "asked feature" to mean that.

**Comment by DaveDavenport** [comment]
Try -kb-cancel 'Super_L'   they are separate keys

**Comment by MagnusOxlund** [comment]
Beautiful, `-kb-cancel Super_L` works. You two should run for congress!

**Comment by sardemff7** [comment]
And other keys may even have unrelated names e.g. "Alt Gr" (not used for US QWERTY but used for French layouts) is `ISO_Level3_Shift` not `Alt_R` (which means it worked already, since we don’t catch that, which is funny).

**Comment by sardemff7** [comment]
Perfect. :-)
